title = "RacineDuCiel"
baseURL = "https://racineduciel.fr/"
enableGitInfo = true
enableEmoji = true
enableRobotsTXT = true
summaryLength = 36

[pagination]
  pagerSize = 15
  path = "page"

defaultContentLanguage = "fr-fr"

[frontmatter]
  lastmod = [":git", ":fileModTime", "lastmod", "date"]

[taxonomies]
  category = "categories"
  tag = "tags"

[related]
  includeNewer = true
  threshold = 30
  toLower = true
  [[related.indices]]
    name = "categories"
    weight = 80
  [[related.indices]]
    name = "tags"
    weight = 60

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.extensions.typographer]
  disable = false

[markup.goldmark.extensions.extras.mark]
  enable = true

[markup.goldmark.extensions.passthrough]
  enable = true
  [markup.goldmark.extensions.passthrough.delimiters]
    block = [['$$', '$$'], ['\\[', '\\]']]
    inline = [['$', '$'], ['\\(', '\\)']]

[privacy.youtube]
  privacyEnhanced = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5

[Languages.fr-fr]
  label = "French"
  locale = "fr-fr"
  contentDir = "content/"
  weight = 1

  [Languages.fr-fr.params]
    mainSections = ["posts"]
    dateFormat = "02/01/2006"
    rssFeedDescription = "summary"
    sitename = "RacineDuCiel"
    description = "Des essais et des notes sur les livres, les idées, les systèmes, le corps et la musique."
    allowedTags = ["certification", "cryptographie", "cybersécurité", "dostoïevski", "écologie", "intelligence artificielle", "littérature", "musique", "philosophie", "santé", "société", "vie privée"]

    [Languages.fr-fr.params.author]
      avatar = "avatar.jpg"
      description = "Des essais et des notes sur les livres, les idées, les systèmes, le corps et la musique."
      name = "RacineDuCiel"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
